### ISSUE TITLE
Question about the source code

### ISSUE THREAD

**Issue by jackey** [kkdai/paxos#1]
here in proposer.go file of line 37. 

```golang
log.Println("[Proposer: prepare recev..")
m := p.nt.recev()
for m == nil {
  log.Println("[Proposer: no msg... ")
  continue
}
```

why not use if ? because if m is ni , this code will block forever , right?
```golang
if m == nil { // }
```

thank u for share this good resource to help me understand the paxos :)

**Comment by kkdai** [comment]
It should be typo mistake.
Thank you, feel free to send your PR.
